### ISSUE TITLE
Add dev settings for default channel

### ISSUE THREAD

**Issue by Soullivaneuh** [maknz/slack#40]
I'm looking for a way to be able to test Slack messages from PHP without disturbing "real" channels.

I'm thinking about two options: `dev_channel` (`string`) and `dev_env` (`bool`).

* `dev_channel`: Specifies a channel to post when the `dev_env` is enabled. Will override all `channel` global or local (on message) settings.
* `dev_env`: Activate the dev env and the `dev_channel` option. Could be use with framework envs for example.

Code example:

```php
$settings = [
    'username' => 'Cyril',
    'channel' => '#accounting',
    'dev_channel' => '#test',
    'dev_env' => true,
    'link_names' => true
];

$client = new Maknz\Slack\Client('http://your.slack.endpoint', $settings);

$client->send('Hello world!'); // Will send to #test
$client->to('#other_channel')->send('Are we rich yet?'); // Will send to #test too
```

What do you think? I'll work on a PR for that.

**Comment by Gummibeer** [comment]
I think that this is solved if #29 is done. Then you can confire everything in your env file - for now you simply can do it your own and set the values in your dev env file for the development channel and in the production env file for the live channel.
I see no need for extra configs like this cause everything is possible with the existing settings and a proper use of the laravel env file.

**Comment by maknz** [comment]
Yeah, I agree with @Gummibeer here. Seems like you can just set up the client to send to #test if you want to do testing, no need for a separate development mode.

#29 has a couple of issues which prevent it being merged. But the same can easily be achieved by having one config file that isn't environment specific (e.g. production) and using `$_ENV` items as the values.

**Comment by Soullivaneuh** [comment]
I'm sorry but this does not solve issue at all.

AFAIK, `SLACK_CHANNEL` will be here for the default channel, so the channel where the message will be sent if not specified.

But if I set `SLACK_CHANNEL` to `#test_channel` and I wrote this code:

```php
$client->to('#other_channel');
```

This will send the message to `#other_channel`, not `#test_channel`.

My request is to have an option to **get rid** of channel requirement and always send it to `#test_channel`.

To compare, it's the same method as `delivery_address` for swiftmailer-bundle: http://symfony.com/doc/current/reference/configuration/swiftmailer.html#delivery-address

@maknz Could you please reopen this issue? I'll work on a PR to demonstrate.

**Comment by Soullivaneuh** [comment]
Maybe we could simplify settings like this:

```php
$settings = [
    'username' => 'Cyril',
    'channel' => '#test',
    'force_channel' => true, // Will send all message to #test, even if the channel is specified on the code.
    'link_names' => true
];
```

**Comment by Gummibeer** [comment]
You can simply use `$client->to(env('SLACK_OTHER_CHANNEL'));` or put it in your config like:

```php
return [
    // slack configs
    'channels' => [
        'one' => env('SLACK_CHANNEL_ONE'),
        'two' => env('SLACK_CHANNEL_TWO'),
    ],
];
```

It's up to you how to solve it, but this package gives you ALL possibilities to do it. But to change the package cause of a very specific usecase isn't the right way.
You can create your own config, put it in the package config or in the services config. Everything can be set by env vars and this way you can solve your problem very simple.

**Comment by Soullivaneuh** [comment]
I'm sorry to insist but this is not a solution.

You're telling me to use env var directly on the code workflow `$client->to(env('SLACK_OTHER_CHANNEL'))`.

What happen if I forgot to use env var for example? The message will be sent on production even if I testing from my local.

And BTW, I don't want to send to `general_test`, `private_channel_test` etc... but to sent **all messages** to **only one** channel on dev env. So your env solution does not solve anything.

> or put it in your config like:

AFAIK there is no `channels` config key under Slack client. And if you are talking about custom config, so I'll have to create a new service class containing slack client to override all the sending process **just** to change a channel? Don't you think it's quite painful?

Or I did not understand this part. In this case, could you please provide a complete working example?

After that, for with my last example, it's juste about adding the `force_channel` that will just be a boolean. Not a big deal IMHO, not hard to maintain and could be useful for many cases.

**Comment by Gummibeer** [comment]
You haven't understand anything.

There is no Problem to add custom keys to the slack config file. In this file you can use env or whatever you want. It's also possible to use env directly in your code - like config() the env() also have a default param.
So there are a lot of useable solutions and the package provides all.
And it's also possible to extend the needed classes and add your solution.

**Comment by Soullivaneuh** [comment]
@Gummibeer Sorry but I still don't see what could help here. So I will explain my concrete case.

With the code from the readme:

```php
$settings = [
    'username' => 'Cyril',
    'channel' => '#test_channel',
    'link_names' => true
];

$client = new Maknz\Slack\Client('http://your.slack.endpoint', $settings);
```

If I call the client like this:

```php
$client->to('#another_orig_channel')->send('Hello world!');
$client->to($dynamicChannelFromAVariable)->send('Hello world!');
```

I want the messages to be sent to `#test_channel` even if another one is specify on the `to` method.

How to do that **without** modify the `$client->to` parameter at all?

I'm curious to see how to do without adding another config key like `force_channel`. :+1: 

> And it's also possible to extend the needed classes and add your solution.

Yes, so by default returning an overridden instance service instead of the Slack library one from the bundle : https://github.com/nexylan/NexySlackBundle#usage

I would like to provide directly the native Slack instance, especially if the proposed change does not modify all the library workflow, and let final user extends it or not.

I'll propose a PR for a POC.

**Comment by Gummibeer** [comment]
Ok, if it's this variable you just can solve it by using `env("SLACK_FORCE_CHANNEL", $variableChannel)` and don't set the env if not needed.
So yes, for this it could be useful to have a config.

@maknz can you reopen it? Primary cause issuer want to fix it with a propper PR.

**Comment by Soullivaneuh** [comment]
ping @maknz 

I'll try to get some time to make a PR.
